### ISSUE TITLE
Add Dropdown with 'Block' Option for Admins in Approved Projects

### ISSUE THREAD

**Issue by RaoVrn** [MentorTeamSync/teamsync_Infosys_Internship_Oct2024#117]
Add a dropdown menu for admins in the Approved Projects section with a "**Block**" option.

The "**Block**" feature should:
- Stop the addition of new members to the project.

This will provide admins with better control over managing approved projects.

<img src="https://github.com/user-attachments/assets/ff2c8b35-5dfe-4ba3-9ecd-9fa43be2a2c1" width="800"/>

**Comment by rovertrack** [comment]
do you want the block option on each project or
on top right of screen a block option which is gonna let you select which projects to block??
