### ISSUE TITLE
Feature Addition: Configure backend api with reset password frontend

### ISSUE THREAD

**Issue by ShubhamPatel2305** [MentorTeamSync/teamsync_Infosys_Internship_Oct2024#18]
Backend routes for password reset details: 

POST request on http://localhost:3001/user/reset which expects a 
body: {email:""} and then this route will send mail of reset password to that mail and respond with status codes: 200 or 400. 

PUT request on http://localhost:3001/user/reset which expects a 
body: {email:"", password:"",resetOtp:""} 
and then this route will verify otp and update user password and respond with status codes: 200 or 400.

**Comment by vthuan-dev** [comment]
i would like to resolve your issue, pls assign me to help you in this one . Thank u

**Comment by ShubhamPatel2305** [comment]
You can start contributing no need to assign it just make sure to add the line resolved #issue name in the pull request comment

**Comment by vthuan-dev** [comment]
but i without .env for this project

**Comment by btwshivam** [comment]
> but i without .env for this project

hey! Are you from from our team? This project is certainly for the team only!

**Comment by vthuan-dev** [comment]
hmm , hi @btwshivam  i do a task of foss course and i would like only resolve a issue on github with tag #goodfirstissue to complete my task

**Comment by btwshivam** [comment]
> hmm , hi @btwshivam i do a task of foss course and i would like only resolve a issue on github with tag #goodfirstissue to complete my task

@vthuan-dev I'm sorry to say that this repo is only for those selected for this Infosys internship. I hope that makes sense to you!

**Comment by vthuan-dev** [comment]
@btwshivam  thank you <3
