### ISSUE TITLE
OTP Not Received During Signup

### ISSUE THREAD

**Issue by RaoVrn** [MentorTeamSync/teamsync_Infosys_Internship_Oct2024#214]
When trying to sign up, the OTP isn’t being sent, stopping users from completing the signup. Please check the OTP system to make sure it’s working.

![image](https://github.com/user-attachments/assets/4f238f23-49e3-4eed-8631-f0dbe0eb97f6)

**Comment by ShubhamPatel2305** [comment]
Mailer pass updated and issue solved, refer to new .env file in teams for further reference.
