### ISSUE TITLE
Admin dashboard not rendering

### ISSUE THREAD

**Issue by ShubhamPatel2305** [MentorTeamSync/teamsync_Infosys_Internship_Oct2024#91]
https://github.com/user-attachments/assets/c6667fd1-b0e0-458a-ab04-8665826302a0

**Comment by ShubhamPatel2305** [comment]
@Tejashree1962 @LikhithaTMurthy @Keerthana86

**Comment by LikhithaTMurthy** [comment]
@ShubhamPatel2305 It's working fine for me

https://github.com/user-attachments/assets/31a9157a-abf3-4d98-adef-f41a7960202f
